language: python
osx_image: xcode9.4
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      python: 2.6
      env: TOXENV=py26
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env: TOXENV=py26
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
      dist: xenial
      sudo: true
      
before_install:
   # For Python 3.6+ machine, horton 3 IOData is installed from source. For Python 2.7 machine, horton 2 is installed from conda.
   # From the documentation, horton 3 works with Python 3.6+ and horton 2 does with Python 2.7
   #
   # h5py is needed for both Horton 2 and Horton 3.
   #
   # For Open Babel,
   # - 3.5: Use the latest version from PyPI and build the bindings to the
   #   OS-provided libraries. The Ubuntu package doesn't install a pkgconfig
   #   file for the OB setup.py file to find, so it incorrectly guesses header
   #   and library paths under /usr/local. Pass the correct paths to the
   #   underlying "python setup.py build_ext" command.
   # - >= 3.6: Use the latest version from conda.
   - |
     if [[ $(echo "$TRAVIS_PYTHON_VERSION >= 3.6" | bc -l) == 1 ]];
     then
         wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
         bash miniconda.sh -b -p $HOME/miniconda -u
         export PATH="$HOME/miniconda/bin:$PATH"

         hash -r
         conda config --add channels conda-forge
         conda config --add channels psi4
         conda config --set always_yes yes --set changeps1 no --set channel_priority flexible
         conda update -q conda
         conda info -a
         conda create -q -n condaenv python=$TRAVIS_PYTHON_VERSION ci-psi4 openbabel psi4

         source activate condaenv
         conda install pytest pytest-cov codecov pytest-shutil
         python -m pip install h5py pyscf
         python -m pip install git+https://github.com/theochem/iodata.git

         conda list
     else
         # Python 3.5
         sudo apt install libopenbabel-dev
         python -m pip install --global-option=build_ext --global-option='-I/usr/include/openbabel3' --global-option='-L/usr/lib/openbabel3' openbabel
         python -m pip install -U pytest pytest-cov h5py
     fi

install:
  - pip install pytest
  - pip install cclib
  - python setup.py install
  - ./.travis-install.sh

script:
  - pytest -v
